# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3ee69fec937eb546f412a109192ff711253b2387c8640c366a5292e27788f9532b94f706ed01883ec90dc33146d121af32f6b24f7cbb7514d01fd5bebd50c8

test:
  secret_key_base: 09b9173e45456711a3c901a0fa3e56ef84bfb148a5927ed7d2a868b3b5cd83cb6427eb0f8bdcb9a9c9dcf23fa43c74c1a818a7cd2224267390b3ccd48684c0d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
